name: synthia
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pytest
  - numpy
  - scipy
  - xarray
  - bottleneck
  - matplotlib
  - seaborn
  - jupyter
  - pip
  - setuptools
  - sphinx
  - sphinx-autobuild
  - sphinx_rtd_theme
  - myst-parser
  - nbsphinx
  - sphinxcontrib-bibtex
  - sphinx-copybutton
  - pip:
    - pyvinecopulib